[2024-11-12T03:29:30.935+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T03:29:31.027+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_analytics_extended.run_dbt_moving_average_NVDA manual__2024-11-12T03:22:50.065327+00:00 [queued]>
[2024-11-12T03:29:31.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_analytics_extended.run_dbt_moving_average_NVDA manual__2024-11-12T03:22:50.065327+00:00 [queued]>
[2024-11-12T03:29:31.057+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-12T03:29:31.144+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_moving_average_NVDA> on 2024-11-12 03:22:50.065327+00:00
[2024-11-12T03:29:31.188+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11242) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T03:29:31.210+0000] {standard_task_runner.py:63} INFO - Started process 11257 to run task
[2024-11-12T03:29:31.194+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_analytics_extended', 'run_dbt_moving_average_NVDA', 'manual__2024-11-12T03:22:50.065327+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpa9n3dd34']
[2024-11-12T03:29:31.220+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask run_dbt_moving_average_NVDA
[2024-11-12T03:29:31.443+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_analytics_extended.run_dbt_moving_average_NVDA manual__2024-11-12T03:22:50.065327+00:00 [running]> on host d99256b0cb87
[2024-11-12T03:29:31.600+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_analytics_extended' AIRFLOW_CTX_TASK_ID='run_dbt_moving_average_NVDA' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T03:22:50.065327+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T03:22:50.065327+00:00'
[2024-11-12T03:29:31.603+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T03:29:31.605+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T03:29:31.607+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --models moving_average']
[2024-11-12T03:29:31.628+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T03:29:31.631+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-11-12T03:29:31.632+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-12T03:29:31.633+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T03:29:31.651+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-12T03:29:31.661+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_price_analytics_extended, task_id=run_dbt_moving_average_NVDA, run_id=manual__2024-11-12T03:22:50.065327+00:00, execution_date=20241112T032250, start_date=20241112T032931, end_date=20241112T032931
[2024-11-12T03:29:31.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 144 for task run_dbt_moving_average_NVDA (Bash command failed. The command returned a non-zero exit code 127.; 11257)
[2024-11-12T03:29:31.712+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T03:29:31.760+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T03:29:31.767+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
