[2024-11-14T23:46:19.890+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: YfinanceToSnowflake.load manual__2024-11-14T23:45:17.002946+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
