[2024-11-14T23:40:43.137+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stock_price_analytics_extended.load90DaysDataToSnowflake manual__2024-11-14T23:38:28.819874+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
