[2024-11-12T03:28:40.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T03:28:40.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_analytics_extended.run_dbt_moving_average_NVDA scheduled__2024-11-11T00:00:00+00:00 [queued]>
[2024-11-12T03:28:40.697+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_analytics_extended.run_dbt_moving_average_NVDA scheduled__2024-11-11T00:00:00+00:00 [queued]>
[2024-11-12T03:28:40.698+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-12T03:28:40.771+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_dbt_moving_average_NVDA> on 2024-11-11 00:00:00+00:00
[2024-11-12T03:28:40.875+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=11157) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T03:28:40.879+0000] {standard_task_runner.py:63} INFO - Started process 11171 to run task
[2024-11-12T03:28:40.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_analytics_extended', 'run_dbt_moving_average_NVDA', 'scheduled__2024-11-11T00:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpji3scfbg']
[2024-11-12T03:28:40.885+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask run_dbt_moving_average_NVDA
[2024-11-12T03:28:41.064+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_analytics_extended.run_dbt_moving_average_NVDA scheduled__2024-11-11T00:00:00+00:00 [running]> on host d99256b0cb87
[2024-11-12T03:28:41.295+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_analytics_extended' AIRFLOW_CTX_TASK_ID='run_dbt_moving_average_NVDA' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T00:00:00+00:00'
[2024-11-12T03:28:41.306+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T03:28:41.316+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-12T03:28:41.327+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --models moving_average']
[2024-11-12T03:28:41.359+0000] {subprocess.py:86} INFO - Output:
[2024-11-12T03:28:41.360+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-11-12T03:28:41.362+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-12T03:28:41.369+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T03:28:41.395+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-12T03:28:41.406+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_analytics_extended, task_id=run_dbt_moving_average_NVDA, run_id=scheduled__2024-11-11T00:00:00+00:00, execution_date=20241111T000000, start_date=20241112T032840, end_date=20241112T032841
[2024-11-12T03:28:41.431+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 139 for task run_dbt_moving_average_NVDA (Bash command failed. The command returned a non-zero exit code 127.; 11171)
[2024-11-12T03:28:41.449+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T03:28:41.494+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T03:28:41.497+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
