[2024-11-12T02:00:03.162+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T02:00:03.808+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.load90DaysDataToSnowflake manual__2024-11-12T01:58:16.776719+00:00 [queued]>
[2024-11-12T02:00:03.898+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.load90DaysDataToSnowflake manual__2024-11-12T01:58:16.776719+00:00 [queued]>
[2024-11-12T02:00:03.916+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T02:00:04.060+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load90DaysDataToSnowflake> on 2024-11-12 01:58:16.776719+00:00
[2024-11-12T02:00:04.282+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7207) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T02:00:04.398+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'StockForcastingNext7WorkingDaysTodayOnward', 'load90DaysDataToSnowflake', 'manual__2024-11-12T01:58:16.776719+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpaat5xqsg']
[2024-11-12T02:00:06.669+0000] {standard_task_runner.py:63} INFO - Started process 7231 to run task
[2024-11-12T02:00:06.669+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask load90DaysDataToSnowflake
[2024-11-12T02:00:07.011+0000] {task_command.py:426} INFO - Running <TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.load90DaysDataToSnowflake manual__2024-11-12T01:58:16.776719+00:00 [running]> on host d99256b0cb87
[2024-11-12T02:00:07.702+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockForcastingNext7WorkingDaysTodayOnward' AIRFLOW_CTX_TASK_ID='load90DaysDataToSnowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T01:58:16.776719+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-12T01:58:16.776719+00:00'
[2024-11-12T02:00:07.708+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T02:00:07.737+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T02:00:07.760+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 42, in load90DaysDataToSnowflake
    cur = return_snowflake_conn()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 14, in return_snowflake_conn
    conn = hook.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 286, in get_conn
    conn_config = self._get_conn_params()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 185, in _get_conn_params
    conn = self.get_connection(self.snowflake_conn_id)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_Forcasting` isn't defined
[2024-11-12T02:00:07.819+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=StockForcastingNext7WorkingDaysTodayOnward, task_id=load90DaysDataToSnowflake, run_id=manual__2024-11-12T01:58:16.776719+00:00, execution_date=20241112T015816, start_date=20241112T020003, end_date=20241112T020007
[2024-11-12T02:00:07.906+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task load90DaysDataToSnowflake (The conn_id `snowflake_Forcasting` isn't defined; 7231)
[2024-11-12T02:00:07.968+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T02:00:08.069+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
