[2024-11-15T01:04:07.504+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-15T01:03:25.262113+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
