[2024-11-12T01:02:31.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-12T01:02:31.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data scheduled__2024-11-11T00:00:00+00:00 [queued]>
[2024-11-12T01:02:31.816+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data scheduled__2024-11-11T00:00:00+00:00 [queued]>
[2024-11-12T01:02:31.817+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-12T01:02:32.027+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_stock_data> on 2024-11-11 00:00:00+00:00
[2024-11-12T01:02:32.254+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'StockForcastingNext7WorkingDaysTodayOnward', 'extract_stock_data', 'scheduled__2024-11-11T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmp7ypkc903']
[2024-11-12T01:02:32.315+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask extract_stock_data
[2024-11-12T01:02:32.324+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4682) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-12T01:02:32.343+0000] {standard_task_runner.py:63} INFO - Started process 4707 to run task
[2024-11-12T01:02:33.124+0000] {task_command.py:426} INFO - Running <TaskInstance: StockForcastingNext7WorkingDaysTodayOnward.extract_stock_data scheduled__2024-11-11T00:00:00+00:00 [running]> on host d99256b0cb87
[2024-11-12T01:02:33.877+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='StockForcastingNext7WorkingDaysTodayOnward' AIRFLOW_CTX_TASK_ID='extract_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-11T00:00:00+00:00'
[2024-11-12T01:02:33.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-12T01:02:34.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-12T01:02:34.300+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Conn_Forcasting_DagFile.py", line 19, in extract_stock_data
    API_KEY = Variable.get("api_key")
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable api_key does not exist'
[2024-11-12T01:02:34.975+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=StockForcastingNext7WorkingDaysTodayOnward, task_id=extract_stock_data, run_id=scheduled__2024-11-11T00:00:00+00:00, execution_date=20241111T000000, start_date=20241112T010231, end_date=20241112T010234
[2024-11-12T01:02:35.356+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task extract_stock_data ('Variable api_key does not exist'; 4707)
[2024-11-12T01:02:35.521+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-12T01:02:36.144+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T01:02:36.194+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
