[2024-11-15T04:37:54.079+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: YfinanceToSnowflake.extract_stock_data manual__2024-11-15T04:37:16.252507+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
