[2024-11-14T23:57:17.353+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T23:57:17.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-14T23:57:00.029155+00:00 [queued]>
[2024-11-14T23:57:17.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-14T23:57:00.029155+00:00 [queued]>
[2024-11-14T23:57:17.744+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T23:57:17.816+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 23:57:00.029155+00:00
[2024-11-14T23:57:17.910+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'YfinanceToSnowflake', 'dbt_run', 'manual__2024-11-14T23:57:00.029155+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/yfinance_to_snowflake.py', '--cfg-path', '/tmp/tmpwu8h44fe']
[2024-11-14T23:57:17.966+0000] {standard_task_runner.py:91} INFO - Job 280: Subtask dbt_run
[2024-11-14T23:57:17.977+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4206) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T23:57:17.989+0000] {standard_task_runner.py:63} INFO - Started process 4231 to run task
[2024-11-14T23:57:18.572+0000] {task_command.py:426} INFO - Running <TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-14T23:57:00.029155+00:00 [running]> on host 5bbe89177473
[2024-11-14T23:57:18.896+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YfinanceToSnowflake' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T23:57:00.029155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T23:57:00.029155+00:00'
[2024-11-14T23:57:18.902+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T23:57:18.908+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T23:57:18.910+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/stocks_mau && dbt run --profiles-dir /opt/***/stocks_mau']
[2024-11-14T23:57:18.946+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T23:57:42.709+0000] {subprocess.py:93} INFO - [0m23:57:42  Running with dbt=1.8.7
[2024-11-14T23:57:55.679+0000] {subprocess.py:93} INFO - [0m23:57:55  Registered adapter: snowflake=1.8.4
[2024-11-14T23:57:58.317+0000] {subprocess.py:93} INFO - [0m23:57:58  Encountered an error:
[2024-11-14T23:57:58.318+0000] {subprocess.py:93} INFO - Compilation Error in snapshot stock_prices_snapshot (snapshots/snaps.sql)
[2024-11-14T23:57:58.323+0000] {subprocess.py:93} INFO -   invalid syntax for function call expression
[2024-11-14T23:57:58.324+0000] {subprocess.py:93} INFO -     line 4
[2024-11-14T23:57:58.325+0000] {subprocess.py:93} INFO -       config(
[2024-11-14T23:58:00.475+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-14T23:58:00.479+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T23:58:00.555+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-14T23:58:00.577+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=YfinanceToSnowflake, task_id=dbt_run, run_id=manual__2024-11-14T23:57:00.029155+00:00, execution_date=20241114T235700, start_date=20241114T235717, end_date=20241114T235800
[2024-11-14T23:58:00.644+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 280 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4231)
[2024-11-14T23:58:00.694+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T23:58:00.848+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T23:58:00.882+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
