[2024-11-15T00:00:15.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T00:00:16.068+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-14T23:57:00.029155+00:00 [queued]>
[2024-11-15T00:00:16.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-14T23:57:00.029155+00:00 [queued]>
[2024-11-15T00:00:16.174+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-15T00:00:16.287+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 23:57:00.029155+00:00
[2024-11-15T00:00:16.313+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'YfinanceToSnowflake', 'dbt_run', 'manual__2024-11-14T23:57:00.029155+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/yfinance_to_snowflake.py', '--cfg-path', '/tmp/tmpb1tsmlp2']
[2024-11-15T00:00:16.322+0000] {standard_task_runner.py:91} INFO - Job 283: Subtask dbt_run
[2024-11-15T00:00:16.354+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4364) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-15T00:00:16.359+0000] {standard_task_runner.py:63} INFO - Started process 4384 to run task
[2024-11-15T00:00:16.697+0000] {task_command.py:426} INFO - Running <TaskInstance: YfinanceToSnowflake.dbt_run manual__2024-11-14T23:57:00.029155+00:00 [running]> on host 5bbe89177473
[2024-11-15T00:00:18.143+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YfinanceToSnowflake' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T23:57:00.029155+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T23:57:00.029155+00:00'
[2024-11-15T00:00:18.186+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T00:00:18.190+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-15T00:00:18.233+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/stocks_mau && dbt run --profiles-dir /opt/***/stocks_mau']
[2024-11-15T00:00:18.480+0000] {subprocess.py:86} INFO - Output:
[2024-11-15T00:01:27.333+0000] {subprocess.py:93} INFO - [0m00:01:27  Running with dbt=1.8.7
[2024-11-15T00:01:42.676+0000] {subprocess.py:93} INFO - [0m00:01:42  Registered adapter: snowflake=1.8.4
[2024-11-15T00:01:54.453+0000] {subprocess.py:93} INFO - [0m00:01:54  Encountered an error:
[2024-11-15T00:01:54.460+0000] {subprocess.py:93} INFO - Compilation Error in snapshot stock_prices_snapshot (snapshots/snaps.sql)
[2024-11-15T00:01:54.463+0000] {subprocess.py:93} INFO -   invalid syntax for function call expression
[2024-11-15T00:01:54.466+0000] {subprocess.py:93} INFO -     line 4
[2024-11-15T00:01:54.468+0000] {subprocess.py:93} INFO -       config(
[2024-11-15T00:01:58.320+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-15T00:01:58.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T00:01:58.485+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-15T00:01:58.530+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=YfinanceToSnowflake, task_id=dbt_run, run_id=manual__2024-11-14T23:57:00.029155+00:00, execution_date=20241114T235700, start_date=20241115T000016, end_date=20241115T000158
[2024-11-15T00:01:58.645+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 283 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4384)
[2024-11-15T00:01:58.712+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-15T00:01:58.864+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T00:01:58.875+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
