[2024-11-15T00:13:18.363+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-15T00:13:18.425+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T00:09:53.165924+00:00 [queued]>
[2024-11-15T00:13:18.448+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T00:09:53.165924+00:00 [queued]>
[2024-11-15T00:13:18.448+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-15T00:13:18.476+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-15 00:09:53.165924+00:00
[2024-11-15T00:13:18.497+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5082) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-15T00:13:18.499+0000] {standard_task_runner.py:63} INFO - Started process 5087 to run task
[2024-11-15T00:13:18.497+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'YfinanceToSnowflake', 'dbt_test', 'manual__2024-11-15T00:09:53.165924+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/yfinance_to_snowflake.py', '--cfg-path', '/tmp/tmpud85fgzu']
[2024-11-15T00:13:18.501+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask dbt_test
[2024-11-15T00:13:18.669+0000] {task_command.py:426} INFO - Running <TaskInstance: YfinanceToSnowflake.dbt_test manual__2024-11-15T00:09:53.165924+00:00 [running]> on host 5bbe89177473
[2024-11-15T00:13:19.250+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='YfinanceToSnowflake' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T00:09:53.165924+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T00:09:53.165924+00:00'
[2024-11-15T00:13:19.253+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-15T00:13:19.257+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-15T00:13:19.259+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/stocks_mau && dbt test --profiles-dir /opt/***/stocks_mau']
[2024-11-15T00:13:19.281+0000] {subprocess.py:86} INFO - Output:
[2024-11-15T00:13:29.563+0000] {subprocess.py:93} INFO - [0m00:13:29  Running with dbt=1.8.7
[2024-11-15T00:13:36.393+0000] {subprocess.py:93} INFO - [0m00:13:36  Registered adapter: snowflake=1.8.4
[2024-11-15T00:13:38.669+0000] {subprocess.py:93} INFO - [0m00:13:38  [[33mWARNING[0m]: Deprecated functionality
[2024-11-15T00:13:38.674+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-11-15T00:13:38.675+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-11-15T00:13:38.676+0000] {subprocess.py:93} INFO - information.
[2024-11-15T00:13:39.656+0000] {subprocess.py:93} INFO - [0m00:13:39  Found 4 models, 10 data tests, 2 snapshots, 1 source, 459 macros
[2024-11-15T00:13:39.676+0000] {subprocess.py:93} INFO - [0m00:13:39
[2024-11-15T00:13:40.891+0000] {subprocess.py:93} INFO - [0m00:13:40  Concurrency: 1 threads (target='dev')
[2024-11-15T00:13:40.925+0000] {subprocess.py:93} INFO - [0m00:13:40
[2024-11-15T00:13:41.000+0000] {subprocess.py:93} INFO - [0m00:13:40  1 of 10 START test not_null_moving_average_ .................................... [RUN]
[2024-11-15T00:13:42.322+0000] {subprocess.py:93} INFO - [0m00:13:42  1 of 10 ERROR not_null_moving_average_ ......................................... [[31mERROR[0m in 1.30s]
[2024-11-15T00:13:42.333+0000] {subprocess.py:93} INFO - [0m00:13:42  2 of 10 START test not_null_moving_average_date ................................ [RUN]
[2024-11-15T00:13:43.166+0000] {subprocess.py:93} INFO - [0m00:13:43  2 of 10 PASS not_null_moving_average_date ...................................... [[32mPASS[0m in 0.83s]
[2024-11-15T00:13:43.214+0000] {subprocess.py:93} INFO - [0m00:13:43  3 of 10 START test not_null_moving_average_symbol .............................. [RUN]
[2024-11-15T00:13:45.090+0000] {subprocess.py:93} INFO - [0m00:13:45  3 of 10 PASS not_null_moving_average_symbol .................................... [[32mPASS[0m in 1.85s]
[2024-11-15T00:13:45.131+0000] {subprocess.py:93} INFO - [0m00:13:45  4 of 10 START test not_null_my_first_dbt_model_id .............................. [RUN]
[2024-11-15T00:13:47.457+0000] {subprocess.py:93} INFO - [0m00:13:47  4 of 10 FAIL 1 not_null_my_first_dbt_model_id .................................. [[31mFAIL 1[0m in 2.31s]
[2024-11-15T00:13:47.514+0000] {subprocess.py:93} INFO - [0m00:13:47  5 of 10 START test not_null_my_second_dbt_model_id ............................. [RUN]
[2024-11-15T00:13:49.135+0000] {subprocess.py:93} INFO - [0m00:13:49  5 of 10 PASS not_null_my_second_dbt_model_id ................................... [[32mPASS[0m in 1.61s]
[2024-11-15T00:13:49.147+0000] {subprocess.py:93} INFO - [0m00:13:49  6 of 10 START test not_null_rsi_ ............................................... [RUN]
[2024-11-15T00:13:50.711+0000] {subprocess.py:93} INFO - [0m00:13:50  6 of 10 ERROR not_null_rsi_ .................................................... [[31mERROR[0m in 1.41s]
[2024-11-15T00:13:50.749+0000] {subprocess.py:93} INFO - [0m00:13:50  7 of 10 START test not_null_rsi_date ........................................... [RUN]
[2024-11-15T00:13:52.148+0000] {subprocess.py:93} INFO - [0m00:13:52  7 of 10 PASS not_null_rsi_date ................................................. [[32mPASS[0m in 1.40s]
[2024-11-15T00:13:52.163+0000] {subprocess.py:93} INFO - [0m00:13:52  8 of 10 START test not_null_rsi_symbol ......................................... [RUN]
[2024-11-15T00:13:53.408+0000] {subprocess.py:93} INFO - [0m00:13:53  8 of 10 PASS not_null_rsi_symbol ............................................... [[32mPASS[0m in 1.24s]
[2024-11-15T00:13:53.415+0000] {subprocess.py:93} INFO - [0m00:13:53  9 of 10 START test unique_my_first_dbt_model_id ................................ [RUN]
[2024-11-15T00:13:54.471+0000] {subprocess.py:93} INFO - [0m00:13:54  9 of 10 PASS unique_my_first_dbt_model_id ...................................... [[32mPASS[0m in 1.05s]
[2024-11-15T00:13:54.484+0000] {subprocess.py:93} INFO - [0m00:13:54  10 of 10 START test unique_my_second_dbt_model_id .............................. [RUN]
[2024-11-15T00:13:55.559+0000] {subprocess.py:93} INFO - [0m00:13:55  10 of 10 PASS unique_my_second_dbt_model_id .................................... [[32mPASS[0m in 1.07s]
[2024-11-15T00:13:55.581+0000] {subprocess.py:93} INFO - [0m00:13:55
[2024-11-15T00:13:55.597+0000] {subprocess.py:93} INFO - [0m00:13:55  Finished running 10 data tests in 0 hours 0 minutes and 15.90 seconds (15.90s).
[2024-11-15T00:13:56.678+0000] {subprocess.py:93} INFO - [0m00:13:56
[2024-11-15T00:13:56.691+0000] {subprocess.py:93} INFO - [0m00:13:56  [31mCompleted with 3 errors and 0 warnings:[0m
[2024-11-15T00:13:56.701+0000] {subprocess.py:93} INFO - [0m00:13:56
[2024-11-15T00:13:56.724+0000] {subprocess.py:93} INFO - [0m00:13:56    Database Error in test not_null_moving_average_ (models/input/schema.yml)
[2024-11-15T00:13:56.731+0000] {subprocess.py:93} INFO -   001003 (42000): SQL compilation error:
[2024-11-15T00:13:56.733+0000] {subprocess.py:93} INFO -   syntax error line 13 at position 0 unexpected 'from'.
[2024-11-15T00:13:56.743+0000] {subprocess.py:93} INFO -   syntax error line 14 at position 7 unexpected 'is'.
[2024-11-15T00:13:56.755+0000] {subprocess.py:93} INFO -   compiled code at target/run/stocks_mau/models/input/schema.yml/not_null_moving_average_.sql
[2024-11-15T00:13:56.765+0000] {subprocess.py:93} INFO - [0m00:13:56
[2024-11-15T00:13:56.766+0000] {subprocess.py:93} INFO - [0m00:13:56  [31mFailure in test not_null_my_first_dbt_model_id (models/example/schema.yml)[0m
[2024-11-15T00:13:56.791+0000] {subprocess.py:93} INFO - [0m00:13:56    Got 1 result, configured to fail if != 0
[2024-11-15T00:13:56.802+0000] {subprocess.py:93} INFO - [0m00:13:56
[2024-11-15T00:13:56.818+0000] {subprocess.py:93} INFO - [0m00:13:56    compiled code at target/compiled/stocks_mau/models/example/schema.yml/not_null_my_first_dbt_model_id.sql
[2024-11-15T00:13:56.831+0000] {subprocess.py:93} INFO - [0m00:13:56
[2024-11-15T00:13:56.832+0000] {subprocess.py:93} INFO - [0m00:13:56    Database Error in test not_null_rsi_ (models/input/schema.yml)
[2024-11-15T00:13:56.842+0000] {subprocess.py:93} INFO -   001003 (42000): SQL compilation error:
[2024-11-15T00:13:56.844+0000] {subprocess.py:93} INFO -   syntax error line 13 at position 0 unexpected 'from'.
[2024-11-15T00:13:56.845+0000] {subprocess.py:93} INFO -   syntax error line 14 at position 7 unexpected 'is'.
[2024-11-15T00:13:56.847+0000] {subprocess.py:93} INFO -   compiled code at target/run/stocks_mau/models/input/schema.yml/not_null_rsi_.sql
[2024-11-15T00:13:56.848+0000] {subprocess.py:93} INFO - [0m00:13:56
[2024-11-15T00:13:56.860+0000] {subprocess.py:93} INFO - [0m00:13:56  Done. PASS=7 WARN=0 ERROR=3 SKIP=0 TOTAL=10
[2024-11-15T00:14:00.487+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-15T00:14:00.497+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-15T00:14:00.685+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-15T00:14:00.843+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=YfinanceToSnowflake, task_id=dbt_test, run_id=manual__2024-11-15T00:09:53.165924+00:00, execution_date=20241115T000953, start_date=20241115T001318, end_date=20241115T001400
[2024-11-15T00:14:01.301+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 300 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 5087)
[2024-11-15T00:14:01.398+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-15T00:14:01.837+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-15T00:14:01.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
