[2024-11-14T20:05:33.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T20:05:33.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_analytics_extended.run_all_dbt_models manual__2024-11-14T19:58:34.596128+00:00 [queued]>
[2024-11-14T20:05:33.757+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_analytics_extended.run_all_dbt_models manual__2024-11-14T19:58:34.596128+00:00 [queued]>
[2024-11-14T20:05:33.759+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-14T20:05:33.848+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_all_dbt_models> on 2024-11-14 19:58:34.596128+00:00
[2024-11-14T20:05:33.886+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_analytics_extended', 'run_all_dbt_models', 'manual__2024-11-14T19:58:34.596128+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/Conn_Forcasting_DagFile.py', '--cfg-path', '/tmp/tmpo0weosac']
[2024-11-14T20:05:33.890+0000] {standard_task_runner.py:91} INFO - Job 257: Subtask run_all_dbt_models
[2024-11-14T20:05:33.906+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4682) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T20:05:33.912+0000] {standard_task_runner.py:63} INFO - Started process 4710 to run task
[2024-11-14T20:05:34.088+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_analytics_extended.run_all_dbt_models manual__2024-11-14T19:58:34.596128+00:00 [running]> on host 885fea738fe5
[2024-11-14T20:05:34.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_analytics_extended' AIRFLOW_CTX_TASK_ID='run_all_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T19:58:34.596128+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T19:58:34.596128+00:00'
[2024-11-14T20:05:34.346+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T20:05:34.348+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T20:05:34.353+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/stocks_mau && dbt run']
[2024-11-14T20:05:34.396+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T20:05:34.399+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-11-14T20:05:34.400+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-14T20:05:34.401+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T20:05:34.419+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-14T20:05:34.428+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_price_analytics_extended, task_id=run_all_dbt_models, run_id=manual__2024-11-14T19:58:34.596128+00:00, execution_date=20241114T195834, start_date=20241114T200533, end_date=20241114T200534
[2024-11-14T20:05:34.456+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 257 for task run_all_dbt_models (Bash command failed. The command returned a non-zero exit code 127.; 4710)
[2024-11-14T20:05:34.494+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T20:05:34.522+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T20:05:34.526+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
